main: me.Harrison.Main.Main
name: Core Plugin
author: Harrison
version: 1.0

commands:
  gm:
    aliases: [gamemode]
    description: gm
  spawn:
    description: GO to spawn
  setspawn:
    description: setspawn
  setRules:
    description: setrules
  clear:
    description: clear
  game:
    description: game-commands
  silence:
    description: Silence